### PR TITLE
bug: fix explicit channel setting with conda env.yaml

### LINKED ISSUE #1005: bug(conda): Fail to use conda channel when the env.yaml is given
## Description

Seems that `config.conda_channel` does not work with `install.conda_packages(env=xx)`

https://github.com/tensorchord/envd/blob/main/pkg/lang/ir/conda.go#L99

/cc @kemingy @VoVAllen 

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by VoVAllen**
Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>

Fix #1005

### CODE REVIEW

File: pkg/lang/ir/conda.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ const (
 var (
 	// this file can be used by both conda and mamba
 	// https://mamba.readthedocs.io/en/latest/user_guide/configuration.html#multiple-rc-files
-	condarc = fileutil.EnvdHomeDir(".condarc")
+	condarc = "/opt/conda/.condarc"
```
Comment (gaocegege) [inline pkg/lang/ir/conda.go:42]: lgtm

/cc @kemingy

Comment (kemingy) [reply pkg/lang/ir/conda.go:42]: Will this override https://github.com/tensorchord/envd/blob/d87afda9213fcb334ca55d247ba3c0663b7b180b/pkg/lang/ir/install-conda.sh#L24

But I guess it's okay?

File: e2e/language/testdata/python/conda_channel/build.envd [hunk 2]
```diff
@@ -0,0 +1,10 @@
+def build():
+    config.conda_channel(
+        channel="""
+channels:
+  - defaults
+  - conda-forge # dgllife in env.yaml only works if specify channels here
```
Comment (kemingy) [inline e2e/language/testdata/python/conda_channel/build.envd:6]: https://github.com/tensorchord/envd/blob/d87afda9213fcb334ca55d247ba3c0663b7b180b/pkg/lang/ir/install-conda.sh#L24
Already use `conda-forge`. So not sure if this test case can fail.

Comment (VoVAllen) [reply e2e/language/testdata/python/conda_channel/build.envd:6]: I think it's fine. The condarc in install-conda.sh is used to install python. And the conda_channel is for user configuration, I think it's fine to overwrite?

Comment (kemingy) [reply e2e/language/testdata/python/conda_channel/build.envd:6]: It's okay to override. But this won't be able to detect if the new channel config is right or wrong. Because even if it doesn't work, the default channel is already `conda-froge`, and the test always passes.

Comment (VoVAllen) [reply e2e/language/testdata/python/conda_channel/build.envd]: Changed to use dgl as test target

Comment (VoVAllen) [reply e2e/language/testdata/python/conda_channel/build.envd]: Changed to use dgl which needs `dglteam` channel for testing

**Review by kemingy — APPROVED** [review]
/lgtm
