### PR TITLE
fix: -path and -file bug

### LINKED ISSUE #446: bug(CLI): fail to use both path and file flag in envd up
```
envd up --path ./examples/mnist -f ./examples/mnist/build_gpu.envd 
error: no such file or directory
```

We use the path dir as the cwd, thus we cannot find the file `./examples/mnist/build_gpu.envd `

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* fix #446

### CODE REVIEW

File: pkg/util/fileutil/file.go [hunk 1]
```diff
@@ -51,6 +51,29 @@ func FileExists(filename string) (bool, error) {
 	return !info.IsDir(), nil
 }
 
+// FindFileAbsPath returns the absolute path for the given path and file
+func FindFileAbsPath(path, fileName string) (string, error) {
```
Comment (gaocegege) [inline pkg/util/fileutil/file.go:55]: Could we add a unit test for the func? Thanks!

Comment (kemingy) [reply pkg/util/fileutil/file.go:55]: Sure

Comment (kemingy) [reply pkg/util/fileutil/file.go:55]: Added. PTAL

**Review by gaocegege — APPROVED** [review]
